-- Migration 1: Fix ReadHistory constraint (only last chapter per comic)
-- Migration 2: Create ReadChapters table (all chapters read)

-- ===== PART 1: Fix ReadHistory =====

-- Step 1: Drop old constraint
ALTER TABLE public.read_history DROP CONSTRAINT IF EXISTS unique_chapter_read;

-- Step 2: Delete duplicate entries (keep only the latest per user+comic)
DELETE FROM public.read_history
WHERE id NOT IN (
  SELECT MAX(id)
  FROM public.read_history
  GROUP BY user_id, comic_id
);

-- Step 3: Add new unique constraint (user_id, comic_id only)
ALTER TABLE public.read_history
ADD CONSTRAINT unique_user_comic_history UNIQUE (user_id, comic_id);


-- ===== PART 2: Create ReadChapters Table =====

-- Create table
CREATE TABLE IF NOT EXISTS public.read_chapters (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  comic_id bigint not null references public.comics(id) on delete cascade,
  
  chapter_slug varchar(255) not null,
  read_at timestamp with time zone default now(),

  -- Unique constraint: same user cannot mark same chapter as read twice
  constraint unique_user_chapter unique (user_id, comic_id, chapter_slug)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_read_chapters_user_comic 
ON public.read_chapters(user_id, comic_id);


-- ===== VERIFICATION QUERIES =====

-- Check ReadHistory has no duplicates (should return 0 rows)
SELECT user_id, comic_id, COUNT(*) as count
FROM public.read_history
GROUP BY user_id, comic_id
HAVING COUNT(*) > 1;

-- Check ReadChapters table created
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name = 'read_chapters';

-- Show sample data structure
SELECT 
  'ReadHistory' as table_name,
  COUNT(*) as total_records,
  COUNT(DISTINCT user_id) as unique_users,
  COUNT(DISTINCT comic_id) as unique_comics
FROM public.read_history
UNION ALL
SELECT 
  'ReadChapters' as table_name,
  COUNT(*) as total_records,
  COUNT(DISTINCT user_id) as unique_users,
  COUNT(DISTINCT comic_id) as unique_comics
FROM public.read_chapters;
