-- --- BAGIAN 0: BERSIH-BERSIH (RESET) ---
-- Hapus tabel/view lama jika ada biar tidak error saat create ulang
DROP VIEW IF EXISTS view_popular_comics;
DROP VIEW IF EXISTS view_comic_details;
DROP TABLE IF EXISTS public.read_history;
DROP TABLE IF EXISTS public.bookmarks;
DROP TABLE IF EXISTS public.comic_genres;
DROP TABLE IF EXISTS public.genres;
DROP TABLE IF EXISTS public.comics;
DROP TABLE IF EXISTS public.users;
DROP FUNCTION IF EXISTS update_timestamp CASCADE;

-- --- BAGIAN 1: TABEL UTAMA ---

-- 1. Tabel Users
CREATE TABLE public.users (
  id bigint generated by default as identity primary key,
  username varchar(255) not null unique,
  email varchar(255) not null unique,
  password varchar(255) not null,
  avatar text default null, -- URL atau Path gambar
  role varchar(20) default 'user' check (role in ('user', 'admin')), -- Validasi role
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 2. Tabel Comics (Master Data Komik)
CREATE TABLE public.comics (
  id bigint generated by default as identity primary key,
  slug varchar(255) not null unique, -- ID unik (misal: 'one-piece')
  title varchar(255) not null,
  alternative_title varchar(255),
  author varchar(255),
  status varchar(50),
  cover_url text,
  synopsis text,
  rating decimal(3, 1) default 0,
  type varchar(50), -- Manga/Manhwa/Manhua
  last_sync_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- 3. Tabel Genres
CREATE TABLE public.genres (
  id bigint generated by default as identity primary key,
  name varchar(100) not null unique, -- Contoh: 'Action'
  slug varchar(100) not null unique  -- Contoh: 'action'
);

-- 4. Tabel Penghubung Komik-Genre (Many-to-Many)
CREATE TABLE public.comic_genres (
  comic_id bigint not null references public.comics(id) on delete cascade,
  genre_id bigint not null references public.genres(id) on delete cascade,
  primary key (comic_id, genre_id)
);

-- 5. Tabel Bookmarks
CREATE TABLE public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  comic_id bigint not null references public.comics(id) on delete cascade,
  created_at timestamp with time zone default now(),
  -- Mencegah duplikasi bookmark
  constraint unique_user_bookmark unique (user_id, comic_id)
);

-- 6. Tabel Reading History (Mencatat HANYA CHAPTER TERAKHIR per komik)
-- Untuk halaman Riwayat - show "Lanjutkan Baca Chapter X"
CREATE TABLE public.read_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  comic_id bigint not null references public.comics(id) on delete cascade,
  
  chapter_slug varchar(255) not null, -- Contoh: 'chapter-10'
  read_at timestamp with time zone default now(),

  -- HANYA 1 entry per user per comic (chapter terakhir yang dibaca)
  constraint unique_user_comic_history unique (user_id, comic_id)
);

-- 7. Tabel Read Chapters (Mencatat SEMUA chapter yang dibaca)
-- Untuk halaman Detail - show checkmark pada chapter yang sudah dibaca
CREATE TABLE public.read_chapters (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  comic_id bigint not null references public.comics(id) on delete cascade,
  
  chapter_slug varchar(255) not null, -- Contoh: 'chapter-5'
  read_at timestamp with time zone default now(),

  -- Bisa banyak chapter per comic, tapi tidak boleh duplikat chapter yang sama
  constraint unique_user_chapter unique (user_id, comic_id, chapter_slug)
);

-- --- BAGIAN 2: FITUR LANJUTAN (WAJIB BUAT UAS) ---

-- A. TRIGGER: Auto Update 'updated_at' di Tabel Users
-- Membuat fungsi dulu
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Pasang trigger ke tabel users
CREATE TRIGGER set_timestamp_users
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- B. VIEW: Menyederhanakan Query Detail Komik
-- Menggabungkan data komik dengan list genrenya
CREATE VIEW view_comic_details AS
SELECT 
    c.id,
    c.title,
    c.slug,
    c.rating,
    c.type,
    c.cover_url,
    STRING_AGG(g.name, ', ') AS genre_list -- Hasil: "Action, Fantasy, Isekai"
FROM 
    public.comics c
LEFT JOIN 
    public.comic_genres cg ON c.id = cg.comic_id
LEFT JOIN 
    public.genres g ON g.id = cg.genre_id
GROUP BY 
    c.id;

-- C. INDEXING: Mempercepat Pencarian
CREATE INDEX idx_comics_slug ON public.comics(slug); -- Biar cari komik by URL cepat
CREATE INDEX idx_comics_title ON public.comics(title); -- Biar search bar cepat
CREATE INDEX idx_history_user ON public.read_history(user_id); -- Biar load history user cepat
CREATE INDEX idx_read_chapters_user_comic ON public.read_chapters(user_id, comic_id); -- Biar load read chapters per comic cepat